/**
 * Artifact Type Definitions
 *
 * Core types for the Artifacts system — renderable content generated by the AI
 * (HTML pages, SVGs, Mermaid diagrams, code files) with sandboxed preview.
 */

/** Supported artifact content types */
export type ArtifactType = "html" | "svg" | "mermaid" | "code" | "react" | "markdown";

/** A single artifact generated by the AI within a conversation */
export interface Artifact {
  /** Unique identifier (UUID) */
  id: string;
  /** Conversation thread this artifact belongs to */
  threadId: string;
  /** Message ID that created/last updated this artifact */
  messageId: string;
  /** User-facing display title (e.g., "Login Page", "Architecture Diagram") */
  title: string;
  /** File name with extension for downloads (e.g., "landing-page.html", "logo.svg") */
  fileName: string;
  /** Content type — determines how the artifact is rendered */
  type: ArtifactType;
  /** Programming language for code artifacts (e.g., "typescript", "python") */
  language?: string;
  /** Raw source content (HTML, SVG markup, Mermaid syntax, code, etc.) */
  content: string;
  /** Version number — increments when updated within the same conversation */
  version: number;
  /** ISO 8601 creation timestamp */
  createdAt: string;
  /** ISO 8601 last update timestamp */
  updatedAt: string;
}

/** Metadata extracted from an artifact fence in an AI message */
export interface ParsedArtifact {
  /** Title extracted from the fence attributes */
  title: string;
  /** Content type extracted from the fence attributes */
  type: ArtifactType;
  /** Programming language (if specified) */
  language?: string;
  /** Raw content between the fences */
  content: string;
  /** Start index in the original message string */
  startIndex: number;
  /** End index in the original message string */
  endIndex: number;
}

/** Display metadata for artifact type icons and labels */
export const ARTIFACT_TYPE_META: Record<
  ArtifactType,
  { label: string; icon: string; color: string }
> = {
  html: { label: "HTML", icon: "Globe", color: "text-orange-400" },
  svg: { label: "SVG", icon: "Image", color: "text-pink-400" },
  mermaid: { label: "Diagram", icon: "GitBranch", color: "text-green-400" },
  code: { label: "Code", icon: "Code", color: "text-blue-400" },
  react: { label: "React", icon: "Component", color: "text-cyan-400" },
  markdown: { label: "Markdown", icon: "FileText", color: "text-gray-400" },
};
